package com.example.overlayhud;

import android.widget.FrameLayout;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.view.MotionEvent;
import android.view.View;

public class FloatingButtonView extends View {
    private final Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        public final Preset.Button data;
            private boolean editMode = false;
                private boolean active = false;
                    private OnEditRequestListener editRequestListener;

                        public interface OnEditRequestListener {
                                void onEditRequested(Preset.Button button);
                                    }

                                        public FloatingButtonView(Context ctx, Preset.Button data, boolean editMode) {
                                                super(ctx);
                                                        this.data = data;
                                                                this.editMode = editMode;
                                                                        setAlpha(data.alpha / 255f);
                                                                                setX(data.x);
                                                                                        setY(data.y);
                                                                                                setLayoutParams(new FrameLayout.LayoutParams(data.size, data.size));
                                                                                                        p.setColor(0xFF000000);
                                                                                                            }

                                                                                                                public void setOnEditRequestListener(OnEditRequestListener listener) {
                                                                                                                        this.editRequestListener = listener;
                                                                                                                            }

                                                                                                                                @Override
                                                                                                                                    protected void onDraw(Canvas c) {
                                                                                                                                            float r = Math.min(getWidth(), getHeight()) / 2f;
                                                                                                                                                    c.drawCircle(r, r, r, p);
                                                                                                                                                        }

                                                                                                                                                            @Override
                                                                                                                                                                public boolean onTouchEvent(MotionEvent e) {
                                                                                                                                                                        if (editMode) {
                                                                                                                                                                                    switch (e.getActionMasked()) {
                                                                                                                                                                                                    case MotionEvent.ACTION_DOWN:
                                                                                                                                                                                                                        // Reabrir editor del botón
                                                                                                                                                                                                                                            if (editRequestListener != null) {
                                                                                                                                                                                                                                                                    editRequestListener.onEditRequested(data);
                                                                                                                                                                                                                                                                                            return true;
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                    case MotionEvent.ACTION_MOVE:
                                                                                                                                                                                                                                                                                                                                                                        float nx = getX() + e.getX() - getWidth() / 2f;
                                                                                                                                                                                                                                                                                                                                                                                            float ny = getY() + e.getY() - getHeight() / 2f;
                                                                                                                                                                                                                                                                                                                                                                                                                setX(nx);
                                                                                                                                                                                                                                                                                                                                                                                                                                    setY(ny);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        data.x = (int) nx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data.y = (int) ny;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                invalidate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return super.onTouchEvent(e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                switch (e.getActionMasked()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case MotionEvent.ACTION_DOWN:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ("toggle".equals(data.mode)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            active = !active;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    InputUtils.handleKey(data.key, active);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                active = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        InputUtils.handleKey(data.key, true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Si está en modo "consumo exclusivo", no pasamos eventos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return data.consumeExclusive || data.touchExclusive;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case MotionEvent.ACTION_MOVE:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Si touchExclusive está desactivado, permitimos que el arrastre pase al panel/juego
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return data.consumeExclusive || data.touchExclusive;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case MotionEvent.ACTION_UP:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case MotionEvent.ACTION_CANCEL:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!"toggle".equals(data.mode)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        active = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                InputUtils.handleKey(data.key, false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return data.consumeExclusive || data.touchExclusive;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return super.onTouchEvent(e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            