package com.example.overlayhud;

import android.widget.FrameLayout;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.view.MotionEvent;
import android.view.View;
import android.content.Intent;

public class MousePanelView extends View {
    private final Paint panelPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
        private final Paint cursorPaint = new Paint(Paint.ANTI_ALIAS_FLAG);

            private final Preset.Button data;
                private final boolean editMode;

                    private float lastX = -1, lastY = -1;
                        private float cursorX = -1, cursorY = -1; // posición del puntero

                            public MousePanelView(Context ctx, Preset.Button d, boolean editMode) {
                                    super(ctx);
                                            this.data = d;
                                                    this.editMode = editMode;

                                                            setAlpha(d.alpha / 255f);
                                                                    setX(d.x);
                                                                            setY(d.y);
                                                                                    setLayoutParams(new FrameLayout.LayoutParams(d.size, d.size));

                                                                                            panelPaint.setColor(0x33444444); // gris translúcido para editar
                                                                                                    cursorPaint.setColor(0xFFFFFFFF); // blanco para el puntero
                                                                                                        }

                                                                                                            @Override
                                                                                                                protected void onDraw(Canvas c) {
                                                                                                                        if (editMode) {
                                                                                                                                    // dibujar el área del panel cuando editas
                                                                                                                                                c.drawRect(0, 0, getWidth(), getHeight(), panelPaint);
                                                                                                                                                        }
                                                                                                                                                                if (cursorX >= 0 && cursorY >= 0) {
                                                                                                                                                                            // dibujar el puntero (círculo pequeño)
                                                                                                                                                                                        float r = 15f;
                                                                                                                                                                                                    c.drawCircle(cursorX, cursorY, r, cursorPaint);
                                                                                                                                                                                                            }
                                                                                                                                                                                                                }

                                                                                                                                                                                                                    @Override
                                                                                                                                                                                                                        public boolean onTouchEvent(MotionEvent e) {
                                                                                                                                                                                                                                if (editMode) {
                                                                                                                                                                                                                                            switch (e.getActionMasked()) {
                                                                                                                                                                                                                                                            case MotionEvent.ACTION_DOWN:
                                                                                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                                                                                                case MotionEvent.ACTION_MOVE:
                                                                                                                                                                                                                                                                                                                    float nx = getX() + e.getX() - getWidth() / 2f;
                                                                                                                                                                                                                                                                                                                                        float ny = getY() + e.getY() - getHeight() / 2f;
                                                                                                                                                                                                                                                                                                                                                            setX(nx);
                                                                                                                                                                                                                                                                                                                                                                                setY(ny);
                                                                                                                                                                                                                                                                                                                                                                                                    data.x = (int) nx;
                                                                                                                                                                                                                                                                                                                                                                                                                        data.y = (int) ny;
                                                                                                                                                                                                                                                                                                                                                                                                                                            invalidate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return super.onTouchEvent(e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            switch (e.getActionMasked()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case MotionEvent.ACTION_DOWN:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lastX = e.getRawX();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lastY = e.getRawY();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (cursorX < 0 || cursorY < 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursorX = getWidth() / 2f;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursorY = getHeight() / 2f;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                invalidate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case MotionEvent.ACTION_MOVE:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        float dx = e.getRawX() - lastX;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            float dy = e.getRawY() - lastY;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lastX = e.getRawX();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lastY = e.getRawY();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursorX += dx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursorY += dy;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // limitar dentro de la pantalla
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (cursorX < 0) cursorX = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (cursorY < 0) cursorY = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (cursorX > getWidth()) cursorX = getWidth();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (cursorY > getHeight()) cursorY = getHeight();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // enviar broadcast al servicio de accesibilidad
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Intent i = new Intent(MouseAccessibilityService.ACTION_MOUSE);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            i.putExtra(MouseAccessibilityService.EXTRA_CMD, "MOVE_ONLY");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                i.putExtra(MouseAccessibilityService.EXTRA_X, (int) cursorX);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    i.putExtra(MouseAccessibilityService.EXTRA_Y, (int) cursorY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        getContext().sendBroadcast(i);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            invalidate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case MotionEvent.ACTION_UP:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return super.onTouchEvent(e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        